{{- $root := . -}}
{{- range .Values.mgmtservices }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .id }}
  name: {{ .id }}
spec:
  ports:
    - name: {{ .id }}
      protocol: TCP
      port: {{ .port }}
  selector: {}
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .id }}
subsets:
  - addresses:
    # will load-balance TCP traffic between the following external management
    # server IPs (BMC reverse proxies) regarding this partition
{{- range .ips }}
      - ip: {{ . }}
{{- end }}
    ports:
      - name: {{ .id }}
        protocol: TCP
        port: {{ $root.Values.ports.bmc_reverse_proxy }}
{{- end }}
