---
zitadel_chart_version: "9.13.0"

zitadel_domain: zitadel.{{ metal_control_plane_ingress_dns }}
zitadel_ingress_dns: https://{{ zitadel_domain }}:4443

zitadel_admin_password: Password1!
zitadel_master_key: x123456789012345678901234567891y
zitadel_db_address: zitadel-db
zitadel_db_password: change-me

zitadel_init_image: ghcr.io/metal-stack/zitadel-init
zitadel_init_image_tag: pr-1
