---
metal_control_plane_ip: 172.17.0.1
metal_control_plane_provider_tenant: metal-stack
metal_control_plane_ingress_dns: 172.17.0.1.nip.io
metal_control_plane_stage_name: test
metal_control_plane_namespace: metal-control-plane
metal_control_plane_image_pull_policy: Always

metal_api_bmc_superuser_pwd: change-me

helm_additional_params:
  - "--debug"

monitoring_grafana_github_oauth:
  enabled: false
monitoring_grafana_extra_secret_mounts: []
monitoring_thanos_receive_enabled: false
monitoring_thanos_receive_ingress_enabled: false

monitoring_thanos_receive_ingress_basic_auth: {}
monitoring_thanos_receive_ingress_annotations: []
monitoring_thanos_receive_ingress_tls: {}
