---
metal_stack_release_version: develop

metal_stack_release_vectors:
  - url: oci://ghcr.io/metal-stack/releases:{{ metal_stack_release_version }}
    variable_mapping_path: metal_stack_release.mapping
    include_role_defaults: metal-roles/common/roles/defaults
    oci_cosign_verify_key: "{{ lookup('file', 'cosign.pub') }}"

##
## for development purposes, you can override releases from our image vector here
##

# metal_hammer_image_url: https://images.metal-stack.io/metal-hammer/pull-requests/<pr-number-and-title>/metal-hammer-initrd.img.lz4
# metal_api_image_name:
# metal_api_image_tag:
# metal_apiserver_image_name:
metal_apiserver_image_tag: v0.1.1
# metal_metalctl_image_name:
# metal_metalctl_image_tag:
# metal_masterdata_api_image_name:
# metal_masterdata_api_image_tag:
# metal_console_image_name:
# metal_console_image_tag:
# metal_core_image_name:
# metal_core_image_tag:
# headscale_image_tag: v0.26.1
# headscale_db_backup_restore_sidecar_image_tag: latest
# headscale_db_backup_restore_sidecar_image_name: ghcr.io/metal-stack/backup-restore-sidecar
# headscale_db_image_tag: 17-alpine
# headscale_db_image_name: postgres
# ...
#

##
## for ansible roles
##

# ansible_common_version:
# metal_roles_version:
# metal_ansible_modules_version:

##
## helm charts
##

# metal_helm_chart_version:
# metal_helm_chart_repo:

# further overrides can be looked up in the metal-role projects where the mapping is defined:
# https://github.com/metal-stack/metal-roles/blob/master/defaults/main.yaml
