prometheus_remote_write:
  - url: "http://{{ metal_control_plane_ingress_dns }}:9090/api/v1/write"

prometheus_hosts_content: |
  127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
  ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
  "{{ hostvars['leaf01'].ansible_host }}" leaf01
  "{{ hostvars['leaf02'].ansible_host }}" leaf02
