---
partition_timezone: Europe/Berlin
environment_name: vagrant

partition_id: vagrant
partition_rack_id: test-rack

# The best practice recommendation is to set an MTU of 9,216 for the inter-switch links,
# and an MTU of 9,000 for the server-facing ports, which donâ€™t carry the VXLAN header.
# See: EVPN in the Data center (D. Dutt, p.77)
mtu:
  vxlan: 9216
  default: 9000

partition_nameservers:
  - 192.168.121.1
  - 1.1.1.1
  - 1.0.0.1

mgmt_gateway: 192.168.121.1

# partition_metal_api_addr points to a domain name that in case of Vagrant contains the metal-api box IP.
# This box IP is not known in advance and must be provided during runtime (e.g. via --extra-vars).
partition_metal_api_addr: "{{ api_dns }}"
partition_metal_api_port: 8080
partition_metal_api_protocol: http
partition_metal_api_basepath: /metal/
api_nsq_lookupd: "{{ api_dns }}:4161"

fluentd_logging: false
fluentd_endpoint: "{{ partition_metal_api_addr }}:24224"

metal_core_hmac_key: metal-edit
metal_core_change_boot_order: false

api_dns: api.192.168.121.1.xip.io
public_dns: 192.168.121.1.xip.io

k8s_metal_namespace: metal-control-plane

control_planes:
  vagrant-lab:
    name: vagrant

reconfigure_switch: true
