---
metal_api_image_tag: v0.4.2
metal_metalctl_image_tag: 26-mep-3-implement-reinstall
metal_masterdata_api_image_tag: v0.4.0
metal_console_image_tag: v0.4.0

metal_db_backup_restore_sidecar_image_tag: v0.5.1
ipam_db_backup_restore_sidecar_image_tag: v0.5.1
masterdata_db_backup_restore_sidecar_image_tag: v0.5.1

metal_core_image_tag: v0.4.0
pixiecore_image_tag: 781e3f0a698bbc3ea960c1d288c6606522db05cd

metal_hammer_image_url: http://images.metal-pod.io/metal-hammer/metal-hammer-initrd.img.lz4
