---
metal_set_resource_limits: no
metal_check_api_health_endpoint: http://api.192.168.121.1.xip.io:8080/metal/v1/health

# FIXME must be set to the next tag
metal_api_image_tag: masterdata
metalctl_image_tag: masterdata

metal_api_replicas: 1
metal_api_view_key: metal-view
metal_api_edit_key: metal-edit
metal_api_admin_key: metal-admin
metal_api_sizes:
- id: v1-small-x86
  name: v1-small-x86
  description: The Tiny Virtual
  constraints:
  - type: cores
    min: 1
    max: 4
  - type: memory
    min: "{{ '500MB' | humanfriendly }}"
    max: "{{ '4GB' | humanfriendly }}"
  - type: storage
    min: "{{ '1GB' | humanfriendly }}"
    max: "{{ '10GB' | humanfriendly }}"
metal_api_partitions:
  - id: vagrant
    name: Vagrant Lab
    description: The vagrant lab
    bootconfig:
      kernelurl: https://images.metal-pod.io/metal-kernel/mainline/metal-hammer-kernel
      imageurl: http://images.metal-pod.io/metal-hammer/metal-hammer-initrd.img.lz4
      commandline: console=ttyS0,115200n8 ip=dhcp carrier_timeout=10
    privatenetworkprefixlength: 22
metal_api_networks:
- id: tenant-super-network-vagrant
  name: "Project Super Network"
  description: "Super network of all project networks"
  nat: false
  privatesuper: true
  underlay: false
  destinationprefixes: []
  partitionid: "vagrant"
  prefixes:
  - 10.0.0.0/16

metal_masterdata_api_tls_server_key: "{{ lookup('file', 'certs/masterdata-api/server-key.pem') }}"
metal_masterdata_api_tls_server_cert: "{{ lookup('file', 'certs/masterdata-api/server.pem') }}"
masterdata_api_tenants:
- meta:
    id: fits
    kind: Tenant
    apiversion: v1
    version: 0
  name: FI-TS
  iam_config:
    issuer_config:
      url: ""
      client_id: "auth-go-cli"
    idm_config:
      idm_type: "UX"
    group_config:
      namespace_max_length: 20
  description: FI-TS tenant, which is provider
masterdata_api_projects:
- meta:
    id: 00000000-0000-0000-0000-000000000001
    kind: Project
    apiversion: v1
    version: 0
  name: gardener-seeds
  description: Gardener Seeds Project

metal_console_replicas: 1
