---
metal_core_change_boot_order: false

metal_core_nsq_tls_enabled: false

metal_core_rack_id: test-rack
metal_core_nsq_lookupd_addr: "0.0.0.0.xip.io:4161"

metal_core_log_level: debug

metal_core_consider_hosts_file_resolution: true

metal_core_grpc_port: 50051
metal_core_grpc_ca_cert: "{{ lookup('file', 'certs/ca.pem') }}"
metal_core_grpc_client_cert: "{{ lookup('file', 'certs/grpc/client.pem') }}"
metal_core_grpc_client_key: "{{ lookup('file', 'certs/grpc/client-key.pem') }}"
