---
auditing_meili_secret: geheim
auditing_meili_environment: development

auditing_meili_ingress:
  enabled: true
  hosts:
    - auditing.{{ metal_control_plane_ingress_dns }}

auditing_meili_persistence:
  enabled: true
  size: 10Gi
  storageClass: null
