---
zitadel_endpoint: zitadel.{{ metal_control_plane_namespace }}.svc.cluster.local
zitadel_external_domain: zitadel.{{ metal_control_plane_ingress_dns }}
zitadel_ingress_dns: https://{{ zitadel_external_domain }}:4443
zitadel_port: 8080
zitadel_skip_verify_tls: true
zitadel_insecure: true

zitadel_init_config:
  static_users:
    - first_name: Olli
      last_name: Owner
      email: olli.owner@metal-stack.io
      password: Olli.Owner123!
    - first_name: Gerrit
      last_name: Guest
      email: gerrit.guest@metal-stack.io
      password: Gerrit.Guest123!
  project:
    id: metal-stack
    name: metal-stack
  application:
    # later id will be added but currently not possible with zitadel
    id: metal-stack
    name: metal-stack
    redirect_uri: http://v2.api.172.17.0.1.nip.io:8080/auth/openid-connect/callback
